'use strict';

const Cardapio = [{"REFEICAO":"ARROZ E FEIJ�OMACARR�O AO SUGO PTS AO SUGO","PRATO PRINCIPAL:":" NUGGETS","SALADA:":"ALMEIR�O","SOBREMESA:":"DOCE DE LEITE","SUCO:":"ABACAXI"},{"REFEICAO":"ARROZ INTEGRAL E FEIJ�O ","PRATO PRINCIPAL:":" ERVILHA COM LEGUMES","SALADA:":"ALMEIR�O","SOBREMESA:":"FRUTA","SUCO:":"ABACAXI"},{"REFEICAO":"ARROZ E FEIJ�OAB�BORA SAUT� PTS COM CHUCHU","PRATO PRINCIPAL:":" FRANGO COM AZEITONA","SALADA:":"COUVE COM CEBOLA","SOBREMESA:":"MA��","SUCO:":"ABACAXI"},{"REFEICAO":"ARROZ INTEGRAL E FEIJ�O ","PRATO PRINCIPAL:":" CUSCUZ VEGETARIANO","SALADA:":"COUVE COM CEBOLA","SOBREMESA:":"MA��","SUCO:":"ABACAXI"}];

module.exports = HTMLItArticles;